[project]
name = "mlforge"
version = "0.1.0"
description = "ML Platform for your local machine"
readme = "README.md"
authors = [
    { name = "chonalchendo", email = "110059232+chonalchendo@users.noreply.github.com" }
]
requires-python = ">=3.13.0"
dependencies = [
    "dagster>=1.12.1",
    "dagster-webserver>=1.12.1",
    "dagster-postgres>=0.28.0",
    "dagster-docker>=0.28.0",
    "fastapi>=0.121.1",
    "mlflow>=3.6.0",
    "minio>=7.2.18",
    "evidently>=0.7.15",
    "uvicorn>=0.38.0",
    "cyclopts>=4.2.1",
    "redis>=7.0.1",
    "duckdb>=1.4.1",
    "polars>=1.35.2",
    "pyarrow>=22.0.0",
    "pydantic>=2.12.4",
    "pydantic-settings>=2.11.0",
    "loguru>=0.7.3",
]

[build-system]
requires = ["uv_build>=0.8.8,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "rust-just>=1.43.0",
]
commit = [
    "commitizen>=4.9.1",
    "prek>=0.2.13",
]
check = [
    "ruff>=0.14.4",
    "ty>=0.0.1a25",
]

[tool.uv]
default-groups = ["check", "commit", "dev"]
