name: Bump Version
on:
  push:
    branches: [main]
jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: Bump version and create changelog
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GK_TOKEN }}
          fetch-depth: 0
      - uses: ./.github/actions/setup
      - run: uv sync --group=commit
      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Bump version and create changelog
        run: uv run cz bump --yes --changelog --changelog-to-stdout > body.md
      - name: Push changes
        run: git push --follow-tags
